server:
  type: simple
  applicationContextPath: /
  adminContextPath: /system
  connector:
    type: http
    port: 8080
    useForwardedHeaders: true
  requestLog:
    appenders:
      - type: console
        logFormat: "%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z}] \"%replace(%r){'(?<=client_secret=|id_token=|access_token=|refresh_token=|one_time_token=|code=|token=|email=|password=|username=|user/)([^&]+)', 'xxxx'}\" %s %b \"%i{Referer}\" \"%i{User-Agent}\" %D \"client_id=%reqAttribute{clientId}\" \"%reqAttribute{requestDetails}\" \"XTID=%i{X-Amzn-Trace-Id}\" \"XRID=%header{X-Request-ID}\" \"XFF=%header{X-Forwarded-For}\" \"XRIP=%header{X-Real-IP}\""

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] %7X{userId} %lo{10}: %replace(%m){'(?<=client_secret=|id_token=|access_token=|refresh_token=|one_time_token=|code=|token=|email=|password=|username=|user/)([^&]+)', 'xxxx'} %replace(%ex){'[\r\n]+', '| '} \n"
